### ISSUE TITLE
Difference rCellMax and rangeMax

### ISSUE THREAD

**Issue by adokter** [jspaaks/baltrad-node#1]
https://github.com/jspaaks/baltrad-node/blob/558d7bb3db23aa32df9840e6a50b84e9c3eb0559/crave/testbaltrad.c#L66

rCellMax gives the maximum range up to where the cluttermask is calculated; this area should be somewhat larger than the maximum range up to where the profile data are averaged, such that the cell finding/fringe steps do not suffer from edge effects.

Therefore by default rCellMax = rangeMax + 5 km

**Comment by adokter** [comment]
https://github.com/jspaaks/baltrad-node/blob/558d7bb3db23aa32df9840e6a50b84e9c3eb0559/crave/testbaltrad.c#L70

modify comment:
azimuth direction -> range direction

**Comment by jspaaks** [comment]
Fixed by commit https://github.com/NLeSC/enram/commit/64b0327fb01dd50cde93e1a1e97c7fa20228af64 I still think it would be better to have ``rangeMax = 25000.0f`` and something like ``rangeMaxBuffer = 5000.0f``. Marking solved for now.
