### ISSUE TITLE
reflectivity averaging by classifyGates(), continuing or deprecated?

### ISSUE THREAD

**Issue by adokter** [jspaaks/baltrad-node#11]
The averaging of reflectivity into layers was moved to this function by Martin. Will we continue to use this function or build this functionality from scratch?

**Comment by adokter** [comment]
see also this issue https://github.com/jspaaks/baltrad-node/issues/12
We need to decide whether some of the functionality of this function should be moved elsewhere

**Comment by jspaaks** [comment]
I would like to close this issue if @adokter agrees

**Comment by adokter** [comment]
ok to close
