### ISSUE TITLE
What is the isnan check doing in classifyGates() ?

### ISSUE THREAD

**Issue by adokter** [jspaaks/baltrad-node#13]
The reflectivity profile arrays were assigned NaN values. Layers are given a value zero if there are really no birds, but retain NaN if there is no estimate possible (e.g. because of rain).
https://github.com/NLeSC/enram/blob/611297849897019eaefb3111f819c5105ba3fd2c/ncradar/lib/vol2bird/libvol2bird.c#L553-L561

**Comment by adokter** [comment]
Adriaan, check whether the distinction NaN and 0 is made correctly everywhere.

**Comment by jspaaks** [comment]
@adokter: Is this still a valid issue or has it been resolved under the new approach of using include flags?

**Comment by jspaaks** [comment]
I would like to close this issue if @adokter agrees

**Comment by adokter** [comment]
Yes, ok to close this issue
