### ISSUE TITLE
Calculate bird density from reflectivity

### ISSUE THREAD

**Issue by adokter** [jspaaks/baltrad-node#14]
Adriaan, please elaborate these steps:
1) average logarithmic dBZ values into a linear Z value
2) Calculate the DBZFACTOR from the radar wavelength
3) assume a typical bird radar cross-section
4) calculate bird density

**Comment by adokter** [comment]
1) logarithmic dBZ is converted to linear Z by `exp(0.1*log(10)*dBZ)`

**Comment by adokter** [comment]
2) `DBZFACTOR` is a radar wavelength specific value, see Eq. 2.14 in https://github.com/NLeSC/enram/blob/master/doc/2009-dokter-et-al-wr2009-06-knmi.pdf

`1000 \[Pi]^5/5.3^4 0.93`

**Comment by adokter** [comment]
3) the bird radar cross section is a constant that needs to be assumed. The default value is `SIGMABIRD=11.0` as in 
https://github.com/NLeSC/enram/blob/master/doc/vol2bird-adriaans-version-20140716/vol2birdprof_h5.c#L88

**Comment by adokter** [comment]
4) In the final step, we obtain bird density in units birds/km^3 by calculating `eta/SIGMABIRD`

**Comment by adokter** [comment]
It is useful to report in the profile both `dBZ`, `eta` and `rhobird`

**Comment by jspaaks** [comment]
"The radar wavelength should be extracted from the PVOL rave object" That information is not stored in the PVOL object, although you could get to it by reading the identifier for the radar from the where field, and then looking up the data for that radar

**Comment by adokter** [comment]
OK - in that case the easiest solution for now is probably to have the radar wavelength as an input parameter

**Comment by jspaaks** [comment]
This should be fixed by commit 014d6aa. Closing the issue
