### ISSUE TITLE
Convert reflectivity factors (dB-scale) to reflectivity (linear-scale) before averaging

### ISSUE THREAD

**Issue by adokter** [jspaaks/baltrad-node#15]
This average is incorrect:
https://github.com/jspaaks/baltrad-node/blob/0a51b512d207b28ef532cbda0473c0f02171a973/crave/testbaltrad.c#L423-L424

Averages should be calculated on reflectivities (on a linear Z scale), and not on reflectivity factor values (logarithmic dBZ-scale).

The conversion dBZ to Z is done as follows:
https://github.com/NLeSC/enram/blob/611297849897019eaefb3111f819c5105ba3fd2c/ncradar/lib/vol2bird/libvol2bird.c#L461

Finally, average the Z values into an averaged Z, and convert the averaged Z values back to a dBZ scale, as in `10*log(averagedZ)/log(10)`

Also see issue https://github.com/jspaaks/baltrad-node/issues/12, additional selection on gates needs to be performed before computing this average

**Comment by jspaaks** [comment]
this issue should be solved by a6c40d4,  issue #12 remains though
