### ISSUE TITLE
add outlier removal svdfit

### ISSUE THREAD

**Issue by adokter** [jspaaks/baltrad-node#16]
After a first run of `svdfit` here
https://github.com/jspaaks/baltrad-node/blob/0a51b512d207b28ef532cbda0473c0f02171a973/crave/testbaltrad.c#L441-L442 the following should be added:
1) the residuals of the fit should be calculated (`fabs(yFitted-yObs)`) and compared to the threshold parameter `VDIFMAX` (which is by default 10.0 m/s).
2) All points with a residual is larger than this value should be removed.
3) `hasAzimuthGap` check should be performed again
4) if `hasAzimuthGap` check is passed, `svdfit` should be run again (but now excluding the points marked in step 2)

see Adriaan's reference code:
https://github.com/NLeSC/enram/blob/master/doc/vol2bird-adriaans-version-20140716/vol2birdprof_h5.c#L635-L644

**Comment by adokter** [comment]
See also issue https://github.com/jspaaks/baltrad-node/issues/5, because of this outlier removal step it gets even more complicated to keep track of your array with pseudocolumns and start/end indices - you need to discard all points dropped as outliers, also a lot easier with a multi-dimensional array.

**Comment by adokter** [comment]
Or perhaps even better: move the entire functionality of `hasAzimuthGap` and the outlier removal to `svdfit` itself

**Comment by jspaaks** [comment]
see also untested fix in branch svdfit2x: "https://github.com/jspaaks/baltrad-node/tree/d9bfdcf6082e1ca82f48c88286dece7e0c43d73e"

**Comment by jspaaks** [comment]
This issue has been resolved by 5af7b9f803b851df7578c5128f679bac619974b5 (but note there is a new issue https://github.com/jspaaks/baltrad-node/issues/24)
