### ISSUE TITLE
Check whether the average for each layer is based on sufficient points

### ISSUE THREAD

**Issue by adokter** [jspaaks/baltrad-node#18]
Check whether the reflectivity average (see https://github.com/jspaaks/baltrad-node/blob/0a51b512d207b28ef532cbda0473c0f02171a973/crave/testbaltrad.c#L452
) for each of the three profile types (as specified by `iData`) is based on sufficient points. This check is done as precondition for running `svdfit`. 

Require a minimum number of gates `NDBZMIN` as in:
https://github.com/NLeSC/enram/blob/master/doc/vol2bird-adriaans-version-20140716/vol2birdprof_h5.c#L555-L560

If this condition is not met, the reflectivity estimate for the layer should be set to `FNAN`

**Comment by adokter** [comment]
Adriaan, check why when `iData==2` the threshold is `NGAPMIN*NGAPBIN` instead of `NDBZMIN`

**Comment by adokter** [comment]
For consistency, also use a threshold `NDBZMIN` when `iData==2`

**Comment by jspaaks** [comment]
Commit f62f0ff should fix this issue. Closing.
