### ISSUE TITLE
check value of complex refractive index

### ISSUE THREAD

**Issue by jspaaks** [jspaaks/baltrad-node#19]
https://github.com/jspaaks/baltrad-node/blob/014d6aa2ec314114a61ecb29776339dd3b71a7ac/crave/constants.h#L36

**Comment by adokter** [comment]
Yes this is ok - one small thing: this number is the norm of the complex refractive index, not the refractive index itself, which is a complex number (the real part describes refraction and imaginary part attenuation). It would be nice if the name of the parameter reflects that it is an absolute value or norm.

**Comment by jspaaks** [comment]
Resolved by 6179454cdd1cd966d14e964b3497dd1e1f31d96c and 81afc17aaad0052adcae36624488bd3e3478531a. closing the issue
