### ISSUE TITLE
Differentiate between selections for averaging and svdfit in includeGate()

### ISSUE THREAD

**Issue by adokter** [jspaaks/baltrad-node#24]
Following up on issue https://github.com/jspaaks/baltrad-node/issues/12:

The program should be able to make two types of gate selections, depending on
(1) the profile type `iProfileType` (3 types)
(2) whether we are selecting gates for input of `svdfit`, or whether we are averaging reflectivity values
In principle we could therefore have 3x2=6 different selections of gates, however I like the current simplicity and it may not be necessary to have so many different selections

The only real change necessary is the following: `svdfit` outliers (as classified here: https://github.com/NLeSC/enram/blob/fdf9110ce8386a79e46f4c55a5bf787d6020959e/ncradar/lib/vol2bird/libvol2bird.c#L1464-L1486) should not be discarded in the reflectivity averages, i.e. in the values calculated here: https://github.com/jspaaks/baltrad-node/blob/0d82f17595b3c11160b93cde24597424092daa5a/crave/testbaltrad.c#L498-L522

**Comment by jspaaks** [comment]
I think this issue has been resolved by commit a930cc35e16aa9a4db9bac21e035e734d9fa9885. I @adokter agrees, I'll close this issue
