### ISSUE TITLE
optional output of low elevation scans and corresponding cell/cluttermap

### ISSUE THREAD

**Issue by adokter** [jspaaks/baltrad-node#26]
Add the option to output elevation scans and corresponding cell/cluttermap as two ODIM_H5 scan-objects or files, such that:

1) we can quickly inspect the result of the rain and clutter filtering applied by the algorithm
2) In the near future the altitude profile data will be used to correct several biases in the lowest elevation scan (which contains spatial information up to larger distances). Therefore the different tasks of profiling and extracting 2D images will be intimately linked.

**Comment by jspaaks** [comment]
moved the issue [here](https://github.com/NLeSC/enram/issues/79). Closing this one.
