### ISSUE TITLE
separate specification of range and azimuth intervals for svdfit() and profile averaging

### ISSUE THREAD

**Issue by adokter** [jspaaks/baltrad-node#3]
https://github.com/jspaaks/baltrad-node/blob/558d7bb3db23aa32df9840e6a50b84e9c3eb0559/crave/testbaltrad.c#L81-L84

It is desirable to have the flexibility to specify separate range intervals for the averaging of profile reflectivity values (set by rangeMin and rangeMax), and the range interval over which the svdfit() function fits a radial velocity model (set by RANGMINSTDEV and RANGMAXSTDEV, see https://github.com/NLeSC/enram/blob/master/doc/vol2bird-adriaans-version-20140716/vol2birdprof_h5.c#L52-L55 for the range specification and https://github.com/NLeSC/enram/blob/master/doc/vol2bird-adriaans-version-20140716/vol2birdprof_h5.c#L57-L58 for the azimuth specification). interval (RANGMINSTDEV, RANGMAXSTDEV) should be contained in the interval (rangeMin,RangeMax)

I would like to specify separately
1) the range interval used by svdfit()
2) the range interval and azimuth interval which is used to average values into profiles, i.e. to have the possibility that this is a subsector of the full surveyed area.

**Comment by adokter** [comment]
This functionality requires adjustments in the getListOfSelectedGates() function of libvol2bird:
https://github.com/NLeSC/enram/blob/611297849897019eaefb3111f819c5105ba3fd2c/ncradar/lib/vol2bird/libvol2bird.c#L1124-L1133

**Comment by jspaaks** [comment]
I'm not entirely sure what you mean, but I don't think we should change ``svdfit`` (that doesn't mean we can't change the data that we pass it though. Correct me if I'm wrong but I think ``svdfit`` should always receive a list of [``azimuthAngle``, ``elevationAngle``] and a corresponding list of ``vrad``. We can opt to not include certain combinations of [``azimuthAngle``,``elevationAngle``] (and the corresponding ``vrad``. I don't see why we should pass pre-processed variables such as an average of vrad, as in [``azimuthAngle``,``elevationAngle``] and the corresponding ``vradLocalAvg``.

**Comment by adokter** [comment]
Yes I agree, no need to change `svdfit`, only the selection of gates that are passed that either `svdfit` or the reflectivity averaging subroutines

**Comment by adokter** [comment]
I see now this functionality already exists in the `classifyGates()` function, but the question is whether you want to continue with this function.

**Comment by jspaaks** [comment]
@adokter: Using the new user-configurable options from [here](https://github.com/NLeSC/enram/blob/645cdcfd920266711d774adc787fcb1a572ed387/ncradar/lib/vol2bird/options.conf#L3-L6), I think we can already do all that you describe in the first post without the need for any RANGMINSTDEV and RANGMAXSTDEV variables.

**Comment by adokter** [comment]
No the two are different. svdfit always requires 360 degrees of data and also a certain range of distances, otherwise it won't be able to complete a sensible fit. For the outputted reflectivities you often want to select a certain sector within the data (e.g. to select a window above land versus above sea, as I have done in the past). This is why RANGMINSTDEV and RANGMIN etc should be different.

In my original code the selection of gates for averaging of reflectivity and for doing svdfit were separate tasks. It keeps popping up that these are different things: you might want to run 'svdfit' on a different subset than you want to calcute the reflectivities.

**Comment by jspaaks** [comment]
Perhaps https://github.com/NLeSC/enram/commit/a930cc35e16aa9a4db9bac21e035e734d9fa9885 helps to resolve this.

**Comment by adokter** [comment]
moved this issue to a different repository, see [here](https://github.com/adokter/baltrad/issues/16)
