### ISSUE TITLE
multi-dimensional array instead of pseudocolumns

### ISSUE THREAD

**Issue by adokter** [jspaaks/baltrad-node#5]
https://github.com/jspaaks/baltrad-node/blob/558d7bb3db23aa32df9840e6a50b84e9c3eb0559/crave/testbaltrad.c#L123-L124

I find myself often making mistakes with storing multi-dimensional arrays in a single list. C supports multi-dimensional arrays, why not use them? Makes it much easier to extract the right data from the list later on (sorry for having opinions on the technicalities;)

**Comment by jspaaks** [comment]
Yes, multidimensional arrays are easier indeed. The fact that we don't currently use them is a legacy of earlier code, i.e. the code I started out from. I assume it is the result of having to copy data back and forth to IDL (which only works for one-dimensional arrays). The same thing occurs with Java Native Interface, and I assume, Python. I therefore did not change it. I we ever overhaul the data structures, as in making libvol2bird use RAVE objects directly, we can change this as well if need be, but until that time I prefer not to touch this (as it will literally break all code -- which we then have to fix again).

**Comment by adokter** [comment]
I understand as far as the library goes, but does this also apply to code you are now building from scratch in the 'main'?

**Comment by jspaaks** [comment]
Yes, ``main`` uses libvol2bird, which has one-dimensional data structures, so no matter what the input data structures are, you need to map it to a one-dimensional arrays and a C-struct, e.g. ``dbzImage`` and ``dbzMeta``.

**Comment by jspaaks** [comment]
I propose to leave it as it is for now. In future projects we should take another look at this
