### ISSUE TITLE
discard svdfit results with very low chisq

### ISSUE THREAD

**Issue by adokter** [jspaaks/baltrad-node#9]
https://github.com/jspaaks/baltrad-node/blob/558d7bb3db23aa32df9840e6a50b84e9c3eb0559/crave/testbaltrad.c#L423

A very low `chisq` indicates an unsuccessful fit by `svdfit`, so these layers should be dropped from the profile.

This was originally implemented with a check on `chisq`, which should be above a threshold `SVDMIN`, defined as a fixed parameter with value `(1e-5)`:
https://github.com/NLeSC/enram/blob/master/doc/vol2bird-adriaans-version-20140716/vol2birdprof_h5.c#L103

**Comment by jspaaks** [comment]
should be fixed by a6c40d4
